spring.application.name=icesi_trade
server.port=8080

server.servlet.context-path=/g1/losbandalos
image.base.url=http://localhost:8080/images/


# Configuración de DataSource para PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/icesitrade_db
spring.datasource.username=icesi_user
spring.datasource.password=supersegura123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.level.root=WARN