-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-03-11 15:06:26 COT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE CATEGORIES 
    ( 
     id_category NUMBER  NOT NULL , 
     name        VARCHAR2 (20)  NOT NULL , 
     description VARCHAR2 (150) 
    ) 
;

ALTER TABLE CATEGORIES 
    ADD CONSTRAINT CATEGORIES_PK PRIMARY KEY ( id_category ) ;

CREATE TABLE FAVORITES_PRODUCTS 
    ( 
     id         NUMBER  NOT NULL , 
     "user"     NUMBER  NOT NULL , 
     product    NUMBER  NOT NULL , 
     created_at TIMESTAMP  NOT NULL 
    ) 
;

ALTER TABLE FAVORITES_PRODUCTS 
    ADD CONSTRAINT FAVORITES_PRODUCTS_PK PRIMARY KEY ( id ) ;

CREATE TABLE IMAGES_PRODUCTS 
    ( 
     id      NUMBER  NOT NULL , 
     url     VARCHAR2 (255)  NOT NULL , 
     product NUMBER  NOT NULL 
    ) 
;

ALTER TABLE IMAGES_PRODUCTS 
    ADD CONSTRAINT IMAGES_PRODUCTS_PK PRIMARY KEY ( id ) ;

CREATE TABLE MESSAGES 
    ( 
     id         NUMBER  NOT NULL , 
     content    CLOB  NOT NULL , 
     sender     NUMBER  NOT NULL , 
     receiver   NUMBER  NOT NULL , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
    ) 
;

ALTER TABLE MESSAGES 
    ADD CONSTRAINT pk_messages PRIMARY KEY ( id ) ;

CREATE TABLE NOTIFICATIONS 
    ( 
     id         NUMBER  NOT NULL , 
     type       NUMBER  NOT NULL , 
     read       NUMBER  NOT NULL , 
     "user"     NUMBER  NOT NULL , 
     message    CLOB , 
     created_at TIMESTAMP  NOT NULL 
    ) 
;

ALTER TABLE NOTIFICATIONS 
    ADD CONSTRAINT NOTIFICATIONS_PK PRIMARY KEY ( id ) ;

CREATE TABLE PERMISSIONS 
    ( 
     id          NUMBER  NOT NULL , 
     name        VARCHAR2 (30)  NOT NULL , 
     description VARCHAR2 (300) 
    ) 
;

ALTER TABLE PERMISSIONS 
    ADD CONSTRAINT PERMISSIONS_PK PRIMARY KEY ( id ) ;

CREATE TABLE PRODUCTS 
    ( 
     id          NUMBER  NOT NULL , 
     title       VARCHAR2 (255)  NOT NULL , 
     category    NUMBER  NOT NULL , 
     status      NUMBER  NOT NULL , 
     description CLOB , 
     price       NUMBER (10,2) , 
     location    VARCHAR2 (100) , 
     is_sold     NUMBER  NOT NULL , 
     seller      NUMBER  NOT NULL , 
     created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     updated_at  TIMESTAMP 
    ) 
;

ALTER TABLE PRODUCTS 
    ADD CONSTRAINT ck_products_status 
    CHECK (status IN ('AVAILABLE','SOLD'))
;
ALTER TABLE PRODUCTS 
    ADD CONSTRAINT pk_products PRIMARY KEY ( id ) ;

CREATE TABLE REVIEWS 
    ( 
     id         NUMBER  NOT NULL , 
     rating     NUMBER (1)  NOT NULL , 
     "comment"  CLOB , 
     product    NUMBER , 
     reviewer   NUMBER  NOT NULL , 
     reviewee   NUMBER  NOT NULL , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
    ) 
;

ALTER TABLE REVIEWS 
    ADD 
    CHECK (rating BETWEEN 1 AND 5) 
;

ALTER TABLE REVIEWS 
    ADD CONSTRAINT REVIEWS_PK PRIMARY KEY ( id ) ;

CREATE TABLE ROLE_PERMISSIONS 
    ( 
     id         NUMBER  NOT NULL , 
     role       NUMBER  NOT NULL , 
     permission NUMBER  NOT NULL 
    ) 
;

ALTER TABLE ROLE_PERMISSIONS 
    ADD CONSTRAINT ROLE_PERMISSIONS_PK PRIMARY KEY ( id ) ;

CREATE TABLE ROLES 
    ( 
     id          NUMBER  NOT NULL , 
     name        VARCHAR2 (30)  NOT NULL , 
     description VARCHAR2 (255) 
    ) 
;

ALTER TABLE ROLES 
    ADD CONSTRAINT ROLES_PK PRIMARY KEY ( id ) ;

CREATE TABLE SALES 
    ( 
     id         NUMBER  NOT NULL , 
     buyer      NUMBER  NOT NULL , 
     product    NUMBER  NOT NULL , 
     created_at TIMESTAMP 
    ) 
;

ALTER TABLE SALES 
    ADD CONSTRAINT SALES_PK PRIMARY KEY ( id ) ;

CREATE TABLE TYPE_NOTIFICATION 
    ( 
     id   NUMBER  NOT NULL , 
     name VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE TYPE_NOTIFICATION 
    ADD CONSTRAINT TYPE_NOTIFICATION_PK PRIMARY KEY ( id ) ;

CREATE TABLE USER_ROLES 
    ( 
     id       NUMBER  NOT NULL , 
     USERS_id NUMBER  NOT NULL , 
     ROLES_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE USER_ROLES 
    ADD CONSTRAINT USER_ROLES_PK PRIMARY KEY ( id ) ;

CREATE TABLE USERS 
    ( 
     id         NUMBER  NOT NULL , 
     email      VARCHAR2 (100)  NOT NULL , 
     password   VARCHAR2 (255)  NOT NULL , 
     name       VARCHAR2 (100)  NOT NULL , 
     phone      VARCHAR2 (20) , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
     updated_at TIMESTAMP 
    ) 
;

ALTER TABLE USERS 
    ADD CONSTRAINT USERS_PK PRIMARY KEY ( id ) ;

ALTER TABLE USERS 
    ADD CONSTRAINT USERS_EMAIL_UQ UNIQUE ( email ) ;

ALTER TABLE FAVORITES_PRODUCTS 
    ADD CONSTRAINT FAVORITES_PRODUCTS_PRODUCTS_FK FOREIGN KEY 
    ( 
     product
    ) 
    REFERENCES PRODUCTS 
    ( 
     id
    ) 
;

ALTER TABLE FAVORITES_PRODUCTS 
    ADD CONSTRAINT FAVORITES_PRODUCTS_USERS_FK FOREIGN KEY 
    ( 
     "user"
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE IMAGES_PRODUCTS 
    ADD CONSTRAINT IMAGES_PRODUCTS_PRODUCTS_FK FOREIGN KEY 
    ( 
     product
    ) 
    REFERENCES PRODUCTS 
    ( 
     id
    ) 
;

ALTER TABLE MESSAGES 
    ADD CONSTRAINT MESSAGES_USERS_FK FOREIGN KEY 
    ( 
     sender
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE MESSAGES 
    ADD CONSTRAINT MESSAGES_USERS_FKv2 FOREIGN KEY 
    ( 
     receiver
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE NOTIFICATIONS 
    ADD CONSTRAINT NOTIFICATIONS_TYPE_NOTIFICATION_FK FOREIGN KEY 
    ( 
     type
    ) 
    REFERENCES TYPE_NOTIFICATION 
    ( 
     id
    ) 
;

ALTER TABLE NOTIFICATIONS 
    ADD CONSTRAINT NOTIFICATIONS_USERS_FK FOREIGN KEY 
    ( 
     "user"
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE PRODUCTS 
    ADD CONSTRAINT PRODUCTS_CATEGORIES_FK FOREIGN KEY 
    ( 
     category
    ) 
    REFERENCES CATEGORIES 
    ( 
     id_category
    ) 
;

ALTER TABLE PRODUCTS 
    ADD CONSTRAINT PRODUCTS_USERS_FK FOREIGN KEY 
    ( 
     seller
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE REVIEWS 
    ADD CONSTRAINT REVIEWS_PRODUCTS_FK FOREIGN KEY 
    ( 
     product
    ) 
    REFERENCES PRODUCTS 
    ( 
     id
    ) 
;

ALTER TABLE REVIEWS 
    ADD CONSTRAINT REVIEWS_USERS_FK FOREIGN KEY 
    ( 
     reviewer
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE REVIEWS 
    ADD CONSTRAINT REVIEWS_USERS_FKv2 FOREIGN KEY 
    ( 
     reviewee
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE ROLE_PERMISSIONS 
    ADD CONSTRAINT ROLE_PERMISSIONS_PERMISSIONS_FK FOREIGN KEY 
    ( 
     permission
    ) 
    REFERENCES PERMISSIONS 
    ( 
     id
    ) 
;

ALTER TABLE ROLE_PERMISSIONS 
    ADD CONSTRAINT ROLE_PERMISSIONS_ROLES_FK FOREIGN KEY 
    ( 
     role
    ) 
    REFERENCES ROLES 
    ( 
     id
    ) 
;

ALTER TABLE SALES 
    ADD CONSTRAINT SALES_PRODUCTS_FK FOREIGN KEY 
    ( 
     product
    ) 
    REFERENCES PRODUCTS 
    ( 
     id
    ) 
;

ALTER TABLE SALES 
    ADD CONSTRAINT SALES_USERS_FK FOREIGN KEY 
    ( 
     buyer
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

ALTER TABLE USER_ROLES 
    ADD CONSTRAINT USER_ROLES_ROLES_FK FOREIGN KEY 
    ( 
     ROLES_id
    ) 
    REFERENCES ROLES 
    ( 
     id
    ) 
;

ALTER TABLE USER_ROLES 
    ADD CONSTRAINT USER_ROLES_USERS_FK FOREIGN KEY 
    ( 
     USERS_id
    ) 
    REFERENCES USERS 
    ( 
     id
    ) 
;

CREATE SEQUENCE MESSAGES_id_SEQ 
START WITH 1 
    NOCACHE ;

CREATE OR REPLACE TRIGGER MESSAGES_id_TRG 
BEFORE INSERT ON MESSAGES 
FOR EACH ROW 
BEGIN 
    :NEW.id := MESSAGES_id_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE PRODUCTS_id_SEQ 
START WITH 1 
    NOCACHE ;

CREATE OR REPLACE TRIGGER PRODUCTS_id_TRG 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN 
    :NEW.id := PRODUCTS_id_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE REVIEWS_id_SEQ 
START WITH 1 
    NOCACHE ;

CREATE OR REPLACE TRIGGER REVIEWS_id_TRG 
BEFORE INSERT ON REVIEWS 
FOR EACH ROW 
BEGIN 
    :NEW.id := REVIEWS_id_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE USERS_id_SEQ 
START WITH 1 
    NOCACHE ;

CREATE OR REPLACE TRIGGER USERS_id_TRG 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN 
    :NEW.id := USERS_id_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             35
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
