name: Java CI with Maven

on:
  push:{}
  pull_request:{}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run Maven tests
        run: mvn -B test

      - name: Display Test Reports in Terminal
        run: |
          echo "=== Test Reports ==="
          if [ -d target/surefire-reports ]; then
            for file in target/surefire-reports/*.txt; do
              echo "------ $file ------"
              cat "$file"
            done
          else
            echo "No se encontraron reportes de pruebas."
          fi
